services:
  kafka:
    image: 'bitnami/kafka:latest'
    ports:
      - '9092:9092'
    environment:
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
  producer:
    build:
      context: .
      args:
        - service=producer
      dockerfile: Dockerfile
    depends_on:
      kafka:
        condition: service_started
    environment:
      - kafkaURL=kafka:9092
      - topic=desegmentation-server
  consumer:
    build:
      context: .
      args:
        - service=consumer
      dockerfile: Dockerfile
    depends_on:
      kafka:
        condition: service_started
    environment:
      - kafkaURL=kafka:9092
      - topic=desegmentation-server
